### PR TITLE
ignore fx log

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

fix issue https://github.com/chaos-mesh/chaosd/issues/48, ignore fx logs.

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@Andrewmatilde @shivanshs9 PTAL

**Comment by shivanshs9** [comment]
@WangXiangUSTC I think we can configure their log level to DEBUG instead? :thinking:

**Comment by WangXiangUSTC** [comment]
> @WangXiangUSTC I think we can configure their log level to DEBUG instead? 🤔

Seems that DEBUG will print more log 🤔

**Comment by WangXiangUSTC** [comment]
> @WangXiangUSTC I think we can configure their log level to DEBUG instead? 🤔

Sorry, I make a mistake, I edit your comment, in fact I want to reply it 🤣

**Comment by WangXiangUSTC** [comment]
only print log of go.uber.org/fx in debug mode now, PTAL again @Andrewmatilde @shivanshs9

**Review by shivanshs9 — APPROVED** [review]
LGTM!

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
