### PR TITLE
JVM: refine with byteman-helper

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
1. already implement the stress and gc with [byteman-helper](https://github.com/chaos-mesh/byteman-helper), this pr refine JVM attack with it.
2. the integration test for the JVM run failed but did not report it, fix it.

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
this pr is split from #106, PTAL @cwen0 @Andrewmatilde

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by cwen0** [comment]
@Andrewmatilde PTAL

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
