### PR TITLE
download memStress and stress-ng according to the architecture

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

Close https://github.com/chaos-mesh/chaosd/issues/196

### CODE REVIEW

**Comment by FingerLeader** [comment]
Should I change the target arch of `memStress` in the feature? So that both `stress-ng` and `memStress` can use the same tag.

**Comment by YangKeao** [comment]
> Should I change the target arch of `memStress` in the feature? So that both `stress-ng` and `memStress` can use the same tag.

Good!

**Review by FingerLeader — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by FingerLeader** [comment]
> > Should I change the target arch of `memStress` in the feature? So that both `stress-ng` and `memStress` can use the same tag.
> 
> Good! But you'll also need to modify the chaos mesh.
> 
> Or should I modify the target arch of `stress-ng`? (though they are the same with arch in matrix.)

Considering chaos mesh, maybe change the arch tag of `stress-ng` is better, cause `memStress` has the tag with other tools.

**Comment by STRRL** [comment]
HI @YangKeao @FingerLeader @Andrewmatilde, could we merge this PR now?

**Comment by YangKeao** [comment]
> HI @YangKeao @FingerLeader @Andrewmatilde, could we merge this PR now?

I'll change the architecture tag of the `stress-ng`, so don't merge.

**Pull request merged**
