### PR TITLE
add ci test on arm

### PR DESCRIPTION
**Pull request by YangKeao**
Signed-off-by: YangKeao <yangkeao@chunibyo.icu>

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by YangKeao** [comment]
I don't know why tai-chi-bot doesn't respond. I'll merge this PR manually. If there are any problem with this behavior, feel free to revert it.

**Pull request merged**
