### PR TITLE
bump gopsutil to 3.21.11

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>
Because the original version of gopsutil does not support `TARGET_OS_MAC`, I think we can bump it to the same version(v3.21.11) as chaos mesh.

### CODE REVIEW

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
@Andrewmatilde PTAL

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
