### PR TITLE
add default value of PayloadProcessNum&FillByFAllocate

### PR DESCRIPTION
**Pull request by Andrewmatilde**
fix problem : #117 

Signed-off-by: andrewmatilde <davis6813585853062@outlook.com>

### CODE REVIEW

**Comment by Andrewmatilde** [comment]
PTAL @WangXiangUSTC .

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
