### PR TITLE
rename some file  to keep file naming conventions consistent

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

rename some file, ~~to keep file naming conventions consistent~~ to reduce the length of file names
image

image

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@Andrewmatilde @shivanshs9 PTAL

**Review by shivanshs9 — APPROVED** [review]
LGTM!

**Comment by Andrewmatilde** [comment]
I suggest to rename xxx_command.go to xxx.go in chaosd/cmd/chaosd/ctl/command/xxx_command.go,because command is already the package and folder name.Delete the suffix here  will help to reduce redundancy in file naming.

**Comment by WangXiangUSTC** [comment]
> I suggest to rename xxx_command.go to xxx.go in chaosd/cmd/chaosd/ctl/command/xxx_command.go,because command is already the package and folder name.Delete the suffix here will help to reduce redundancy in file naming.

I agree with you, PTAL again

**Comment by Andrewmatilde** [comment]
LGTM

**Review by Andrewmatilde — APPROVED** [review]

**Pull request merged**
