### PR TITLE
Add json tag for kafka attack

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: FingerLeader <wanxfinger@gmail.com>

### CODE REVIEW

**Comment by FingerLeader** [comment]
PTAL /cc @Hexilee @cwen0

**Review by Hexilee — APPROVED** [review]
LGTM

**Review by g1eny0ung — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
