### PR TITLE
update chaos mesh && minor fix on stress attack

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

### CODE REVIEW

**Comment by WangXiangUSTC** [comment]
@cwen0 PTAL

**Comment by cwen0** [comment]
@WangXiangUSTC Can we set this log level to debug and add a flag to control the log level? We can create an another pr to do it.

```
[2020/12/25 18:12:16.685 +08:00] [INFO] [stress_attack.go:81] ["stressors normalize"] [arguments=" --cpu 1 --cpu-lo
ad 10"]
[2020/12/25 18:12:16.686 +08:00] [INFO] [stress_attack.go:95] ["Start stress-ng process successfully"] [command="/u
sr/bin/stress-ng --cpu 1 --cpu-load 10"]
```

**Review by cwen0 — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
> @WangXiangUSTC Can we set this log level to debug and add a flag to control the log level? We can create an another pr to do it.
> 
> ```
> [2020/12/25 18:12:16.685 +08:00] [INFO] [stress_attack.go:81] ["stressors normalize"] [arguments=" --cpu 1 --cpu-lo
> ad 10"]
> [2020/12/25 18:12:16.686 +08:00] [INFO] [stress_attack.go:95] ["Start stress-ng process successfully"] [command="/u
> sr/bin/stress-ng --cpu 1 --cpu-load 10"]
> ```

OK

**Pull request merged**
