### PR TITLE
package the chaosd and tools into one compressed file

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
users can download this compressed file, and run chaosd directly, don't need to install stress-ng and byteman.

the dir tree looks like:

  - chaosd
  - tools
      - byteman
      - stress-ng

### CODE REVIEW

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Comment by WangXiangUSTC** [comment]
@cwen0 PTAL

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Pull request merged**
