### PR TITLE
support vm attack

### PR DESCRIPTION
**Pull request by WangXiangUSTC**
Signed-off-by: xiang <xiang13225080@163.com>

close issue #25 

usage: 

```shell
./bin/chaosd attack vm -h
vm attack by using virsh

Usage:
  chaosd attack vm attack [flags]

Flags:
  -h, --help             help for vm
  -v, --vm-name string   The name of the vm to be destoryed

Global Flags:
      --log-level string   the log level of chaosd. The value can be 'debug', 'info', 'warn' and 'error'
      --uid string         the experiment ID

```

### CODE REVIEW

**Comment by Andrewmatilde** [comment]
In my opinion,  codes for downloading virsh should be added in Makefile.

**Comment by Andrewmatilde** [comment]
Rest LGTM

**Comment by WangXiangUSTC** [comment]
> In my opinion, codes for downloading virsh should be added in Makefile.

Users need to download `virsh` by `yum` or `apt`, depending on the Linux distribution. I think we can add the download command in the document

**Review by Andrewmatilde — APPROVED** [review]
OK, I agree with you , LGTM

**Review by cwen0 — APPROVED** [review]
LGTM

**Review by Andrewmatilde — APPROVED** [review]
LGTM

**Pull request merged**
